### ISSUE TITLE
Add support for collections in YAML parser

### ISSUE THREAD

**Issue by nmervaillie** [jQAssistant/jqa-yaml2-plugin#1]
I'm using JQA in a microservices context to analyze OpenAPI specifications described in YAML.

The YAML parser works fine, except for collections types : all collection elements are grouped as children of the same parent node. 

Example

In openAPI, API parameters are represented as YAML collections :

```yaml
paths:
  /pets:
    get:
      description: |
        Returns all pets from the system that the user has access to
      operationId: findPets
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
```

As the scanner ignores collections, theirs values are all attached to the same parent, making them quite useless.
![image](https://cloud.githubusercontent.com/assets/1990470/16546316/14e09f00-4147-11e6-8622-e5f7210d19ed.png)

I guess they should be grouped by an intermediate node, representing the collection index.
